purchase:
  security:
    permit-all:
      - /products/**
      - /categories/**
      - /actuator/**
      - /auth/**
      - /v3/api-docs/**
      - /swagger-ui/**
      - /swagger-ui.html
      - /webjars/**
      - /doc.html
      - /error
