server:
  port: 8081

spring:
  application:
    name: purchase-backend
  profiles:
    active: mock
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  config:
    import:
      - application-security.yml
      - application-actuator.yml

